/* =========================================================
   داده‌ی دروس — ۳۰ درس برای هر بخش (HTML / CSS / JavaScript)
   ========================================================= */
window.CODEFARSI_LESSONS = {
  html: [
    { fa: "مقدمه‌ای بر HTML", en: "Introduction to HTML" },
    { fa: "ساختار سند HTML", en: "HTML Document Structure" },
    { fa: "تگ‌های متنی و هدینگ‌ها", en: "Text Tags & Headings" },
    { fa: "پاراگراف‌ها و شکست خط", en: "Paragraphs & Line Breaks" },
    { fa: "لینک‌ها", en: "Links" },
    { fa: "تصاویر", en: "Images" },
    { fa: "لیست‌های مرتب و نامرتب", en: "Ordered & Unordered Lists" },
    { fa: "لیست‌های توصیفی", en: "Description Lists" },
    { fa: "جدول‌ها", en: "Tables" },
    { fa: "جدول‌های پیشرفته (colspan/rowspan)", en: "Advanced Tables (colspan/rowspan)" },
    { fa: "مبانی فرم‌ها", en: "Forms Basics" },
    { fa: "انواع ورودی فرم", en: "Form Input Types" },
    { fa: "ولیدیشن فرم در HTML", en: "Form Validation Attributes" },
    { fa: "عناصر معنایی HTML5", en: "Semantic HTML5 Elements" },
    { fa: "Div و Span", en: "Div & Span" },
    { fa: "کامنت‌گذاری در HTML", en: "Comments in HTML" },
    { fa: "کاراکترهای ویژه (Entities)", en: "HTML Entities" },
    { fa: "آی‌فریم‌ها", en: "Iframes" },
    { fa: "جاسازی صدا و ویدیو", en: "Audio & Video Embedding" },
    { fa: "متا تگ‌ها و مبانی سئو", en: "Meta Tags & SEO Basics" },
    { fa: "ویژگی‌های data-*", en: "Data Attributes" },
    { fa: "دسترسی‌پذیری و ARIA پایه", en: "Accessibility & Basic ARIA" },
    { fa: "مقدمه‌ای بر Canvas", en: "HTML5 Canvas Intro" },
    { fa: "مبانی SVG", en: "SVG Basics" },
    { fa: "فاوآیکون و عناصر head", en: "Favicon & Head Elements" },
    { fa: "کدگذاری کاراکترها", en: "Character Encoding" },
    { fa: "بهترین شیوه‌های HTML", en: "HTML Best Practices" },
    { fa: "دیباگ HTML با DevTools", en: "Debugging HTML with DevTools" },
    { fa: "ساخت یک نوار ناوبری", en: "Building a Navbar" },
    { fa: "پروژه کوچک: صفحه پروفایل", en: "Mini Project: Profile Page" },
  ],
  css: [
    { fa: "مقدمه‌ای بر CSS", en: "Introduction to CSS" },
    { fa: "روش‌های افزودن CSS", en: "Ways to Add CSS" },
    { fa: "مبانی سلکتورها", en: "Selectors Basics" },
    { fa: "سلکتورهای پیشرفته", en: "Advanced Selectors" },
    { fa: "رنگ‌ها", en: "Colors" },
    { fa: "پس‌زمینه‌ها", en: "Backgrounds" },
    { fa: "باکس مدل", en: "The Box Model" },
    { fa: "مارجین و پدینگ", en: "Margin & Padding" },
    { fa: "بوردر و گردکردن گوشه‌ها", en: "Borders & Border Radius" },
    { fa: "تایپوگرافی و فونت‌ها", en: "Typography & Fonts" },
    { fa: "استایل‌دهی متن", en: "Text Styling" },
    { fa: "ویژگی display", en: "The Display Property" },
    { fa: "ویژگی position", en: "The Position Property" },
    { fa: "فلکس‌باکس — مبانی", en: "Flexbox Basics" },
    { fa: "فلکس‌باکس — پیشرفته", en: "Flexbox Advanced" },
    { fa: "CSS Grid — مبانی", en: "CSS Grid Basics" },
    { fa: "CSS Grid — پیشرفته", en: "CSS Grid Advanced" },
    { fa: "Float و Clear", en: "Float & Clear (Legacy)" },
    { fa: "شبه‌کلاس‌ها (Pseudo-classes)", en: "Pseudo-classes" },
    { fa: "شبه‌عنصرها (Pseudo-elements)", en: "Pseudo-elements" },
    { fa: "متغیرهای CSS", en: "CSS Variables" },
    { fa: "ترنزیشن‌ها", en: "Transitions" },
    { fa: "انیمیشن‌ها (keyframes)", en: "Animations (Keyframes)" },
    { fa: "ترنسفورم‌ها", en: "Transforms" },
    { fa: "ریسپانسیو و Media Query", en: "Responsive Design & Media Queries" },
    { fa: "واحدها (px، em، rem، %)", en: "Units (px, em, rem, %)" },
    { fa: "z-index و Stacking Context", en: "Z-index & Stacking Context" },
    { fa: "سایه‌ها (box/text-shadow)", en: "Shadows (Box & Text)" },
    { fa: "بهترین شیوه‌های CSS", en: "CSS Best Practices" },
    { fa: "پروژه کوچک: استایل یک صفحه لندینگ", en: "Mini Project: Styling a Landing Page" },
  ],
  js: [
    { fa: "مقدمه‌ای بر جاوااسکریپت", en: "Introduction to JavaScript" },
    { fa: "متغیرها (var/let/const)", en: "Variables (var/let/const)" },
    { fa: "انواع داده", en: "Data Types" },
    { fa: "عملگرها", en: "Operators" },
    { fa: "شرط‌ها (if/else)", en: "Conditionals (if/else)" },
    { fa: "دستور switch", en: "Switch Statement" },
    { fa: "حلقه‌ها (for/while)", en: "Loops (for/while)" },
    { fa: "آرایه‌ها — مبانی", en: "Arrays Basics" },
    { fa: "متدهای آرایه", en: "Array Methods" },
    { fa: "اشیاء — مبانی", en: "Objects Basics" },
    { fa: "توابع — مبانی", en: "Functions Basics" },
    { fa: "توابع پیکانی (Arrow Functions)", en: "Arrow Functions" },
    { fa: "Scope و Closures", en: "Scope & Closures" },
    { fa: "متدهای رشته‌ای", en: "String Methods" },
    { fa: "Template Literals", en: "Template Literals" },
    { fa: "انتخاب عناصر DOM", en: "DOM Selection" },
    { fa: "دستکاری DOM", en: "DOM Manipulation" },
    { fa: "رویدادها — مبانی", en: "Events Basics" },
    { fa: "Event Bubbling", en: "Event Bubbling" },
    { fa: "فرم‌ها و ولیدیشن در JS", en: "Forms & Validation in JS" },
    { fa: "JSON", en: "JSON" },
    { fa: "Fetch API و مبانی AJAX", en: "Fetch API & AJAX Basics" },
    { fa: "ویژگی‌های ES6 به بعد", en: "ES6+ Features" },
    { fa: "Destructuring", en: "Destructuring" },
    { fa: "Spread و Rest", en: "Spread & Rest" },
    { fa: "مدیریت خطا (try/catch)", en: "Error Handling (try/catch)" },
    { fa: "LocalStorage در جاوااسکریپت", en: "LocalStorage in JavaScript" },
    { fa: "تایمرها (setTimeout/setInterval)", en: "Timers (setTimeout/setInterval)" },
    { fa: "دیباگ با Console", en: "Debugging with Console" },
    { fa: "پروژه پایانی: یک اپلیکیشن کوچک", en: "Final Project: Mini App" },
  ],
};
